version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    docker:
      - image: circleci/ruby:2.6.4

    steps:
      - checkout
      - run:
          name: Deploy Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
